export enum ShiJiaNowColumn {
  UNKNOWN_0 = 0,
  NAME = 1,
  LEVEL = 2,
  RELATIONSHIP_INDEX = 3,
  UNKNOWN_4 = 4,
  COORDINATES = 5,
  INHERITANCE = 6,
  ROYAL_INFLUENCE = 7,
  OTHER_RELATIONS = 8,
  UNKNOWN_9 = 9,
  UNKNOWN_10 = 10,
  ARMY_STRENGTH = 11,
  UNKNOWN_12 = 12,
}

export const OTHER_FAMILY_COLUMN_COUNT = 13
